name: CI Build

on:
  push:
  pull_request:

jobs:
  build-issue:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.28.5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Zephyr (use repo's Zephyr as base)
        run: |
          echo "ZEPHYR_BASE=$GITHUB_WORKSPACE/../zephyr" >> $GITHUB_ENV

      - name: Init Zephyr using west.yml
        run: |
          west init -l .
          west update
          west zephyr-export

      - name: Build for BeagleConnect Freedom
        run: |
          west build -b beagleconnect_freedom -p always .

